---
title: "Visual 1 DC"
output: html_document
date: "2025-12-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)

dreams <- read_csv("/Users/nadyakonadu/Documents/stars-streets-sleep/data/cleaned/mississauga_only.csv")

glimpse(dreams)
```

```{r}
dreams_long <- dreams %>%
  filter(!is.na(emotions_top3)) %>%
  separate_rows(emotions_top3, sep = ",\\s*") %>%
  separate(
    emotions_top3,
    into = c("emotion_raw", "weight"),
    sep = ":",
    convert = TRUE
  )

dreams_long
```
```{r}
dreams_long %>%
  count(emotion_raw, sort = TRUE)
```

```{r}
emotion_map <- c(
  # Joy
  "excitement" = "Joy",
  "desire" = "Joy",
  "caring" = "Joy",
  "approval" = "Joy",
  "amusement" = "Joy",
  "relief" = "Joy",
  "gratitude" = "Joy",
  "optimism" = "Joy",
  "admiration" = "Joy",


  # Sadness
  "sadness" = "Sadness",
  "grief" = "Sadness",
  "disappointment" = "Sadness",
  "remorse" = "Sadness",


  # Anger
  "anger" = "Anger",
  "annoyance" = "Anger",
  "disapproval" = "Anger",
  "disgust" = "Anger",


  # Fear
  "fear" = "Fear",
  "nervousness" = "Fear",
  "embarrassment"= "Fear",


  # Cognitive 
  "confusion" = "Cognitive",
  "curiosity" = "Cognitive",
  "realization" = "Cognitive",
  "surprise" = "Cognitive"

)
```

```{r}
dreams_long <- dreams_long %>%
  mutate(category = recode(emotion_raw, !!!emotion_map))
```

```{r}
dreams_agg <- dreams_long %>%
  group_by(month, category, emotion_raw) %>%
  summarise(
    weight_sum = sum(weight),
    .groups = "drop"
  )

```


```{r}
dreams_final <- dreams_agg %>%
  group_by(month) %>%
  mutate(
    prop = weight_sum / sum(weight_sum)
  ) %>%
  ungroup()
```

```{r}
write_csv(
  dreams_final,
  "/Users/nadyakonadu/Documents/stars-streets-sleep/data/cleaned/dream_emotion_long.csv"
)
```